feat(utils): Crossroad mock server
amp-labs/connectors pull request #1062
Opened 2024-10-07 15:07 UTC by Cobalt0s

2024-10-07 15:07 UTC, Cobalt0s commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/amp-labs/connectors/1062?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1062** <a href="https://app.graphite.dev/github/pr/amp-labs/connectors/1062?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#1061** <a href="https://app.graphite.dev/github/pr/amp-labs/connectors/1061?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1060** <a href="https://app.graphite.dev/github/pr/amp-labs/connectors/1060?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Cobalt0s and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-18 14:31 UTC, jatinsandilya requested changes
@Cobalt0s I see the screenshot/ PR description has a different method name vs the actual code? could you please update the screenshots as well? 

This is what I'm assuming that you'd like the mockServer util to be called, as present in code instead of `Crossroad`. 

```
	return Switch{
		Setup: re.Setup,
		Cases: []Case{{
			If:   re.If,
			Then: re.Then,
		}},
		Default: re.Else,
	}.Server()
```

Please address this otherwise the code changes look good to me! 👍🏼

2024-10-18 18:07 UTC, Cobalt0s commented
@jatinsandilya, sorry for not updating the description. It was called Crossroad with paths, and got renamed to Switch with cases. I changes it just yesterday in response to another PR.

The screenshots and text description is up to date now.

2024-10-21 10:48 UTC, jatinsandilya approved these changes
LGTM 👍🏼

2024-10-21 15:07 UTC, merged