[ENG-793] feat: Add Copper connector
amp-labs/connectors pull request #109
Opened 2024-03-19 08:22 UTC by Listener430

## Catalog variables
No required catalog variables

## Notes

## Testing 
### GET 
URL: <localhost:4444/account> 
![Copper proxy get ok](https://github.com/amp-labs/connectors/assets/95291462/3701eae2-9246-4948-b76d-9a70f0d7f1bb)

### POST
URL: <localhost:4444/people>
![Copper proxy post ok](https://github.com/amp-labs/connectors/assets/95291462/38c0a657-a631-47b6-8661-31e0410779e3)

### PUT
URL: <localhost:4444/people/160213588>
![Cooper proxy put ok](https://github.com/amp-labs/connectors/assets/95291462/0ff369fe-198f-4fe1-b8e7-01f717e6a43a)

### DELETE
URL: <localhost:4444/people/160213590> 
![Copper proxy del ok](https://github.com/amp-labs/connectors/assets/95291462/df9feff6-8e7d-4ad6-95a7-efc5bdfd26c2)

## Pagination
![Copper_pagination_example](https://github.com/amp-labs/connectors/assets/95291462/3ef33277-4e39-4dc8-9e1d-dc503990a867)

2024-03-19 08:23 UTC, Listener430 commented
@RajatPawar, hi, as agreed, sending Copper Connector code separately. Please kindly take a look.

2024-03-19 13:38 UTC, Listener430 commented
@RajatPawar please kindly take a look when you have a second.

2024-03-20 11:20 UTC, RajatPawar commented on providers/catalog.go
> +		BaseURL:  "https://api.copper.com/developer_api/v1",
Can you please not add the version in the Base URL? If they release a new version, we'll have to update it.

2024-03-20 11:20 UTC, RajatPawar requested changes
Can you please not add the version in the Base URL? If they release a new version, we'll have to update it.

2024-03-21 06:26 UTC, RajatPawar commented on providers/catalog.go
> +		BaseURL:  "https://api.copper.com/developer_api/v1",
@Listener430 can you please remove /v1 from the base URL? We don't want to have to update this if they release a v2.

2024-03-21 06:48 UTC, RajatPawar requested changes
[For https://github.com/amp-labs/connectors/pull/109#pullrequestreview-1948601319](https://github.com/amp-labs/connectors/pull/109#pullrequestreview-1948601319)

2024-03-21 06:50 UTC, RajatPawar approved these changes

2024-03-21 06:50 UTC, merged