Make webhook message to map type, recordId and timestamp from webhook
amp-labs/connectors pull request #1251
Opened 2024-12-30 19:15 UTC by jlimatampersand

Test Result

```
jaehyunlim@Jaehyuns-MacBook-Pro connectors % go run ./test/hubspot/record/main.go
time=2024-12-30T11:13:37.128-08:00 level=DEBUG msg="loading credentials file" path=./hubspot-creds.json
time=2024-12-30T11:13:37.130-08:00 level=DEBUG msg="HTTP request" connector=hubspot method=POST url=https://api.hubapi.com/crm/v3/objects/contacts headers="[{Key:Accept Value:application/json}]" bodySize=233
time=2024-12-30T11:13:37.907-08:00 level=DEBUG msg="HTTP request" connector=hubspot method=POST url=https://api.hubapi.com/crm/v3/objects/contacts/batch/read headers="[{Key:Accept Value:application/json}]" bodySize=51
[
  {
    "fields": null,
    "raw": {
      "archived": false,
      "createdAt": "2024-12-30T19:13:37.628Z",
      "id": "88049383345",
      "properties": {
        "createdate": "2024-12-30T19:13:37.628Z",
        "email": "wendygleason@hammes.info",
        "firstname": "Jonathan",
        "hs_object_id": "88049383345",
        "lastmodifieddate": "2024-12-30T19:13:37.628Z",
        "lastname": "Feil"
      },
      "updatedAt": "2024-12-30T19:13:37.628Z"
    },
    "id": "88049383345"
  }
]
```

2024-12-31 01:56 UTC, laurenzlong commented
@jlimatampersand sorry I didn't realize that's why you were using pointer types, I actually prefer https://github.com/amp-labs/connectors/pull/1238 over this approach. Strictly typing is preferred over using `map[string]any` since the code is more readable. I'm going to close this PR, feel free to merge https://github.com/amp-labs/connectors/pull/1238

2024-12-31 02:11 UTC, laurenzlong requested changes
@jlimatampersand I actually prefer https://github.com/amp-labs/connectors/pull/1238 over this approach. Strictly typing is preferred over using map[string]any since the code is more readable. I didn't mean that you shouldn't use pointer types, I meant that you shouldn't use `*string`. Even if you use `string` type, omitempty will still omit empty strings when you JSON marshal. See https://go.dev/play/p/eUyr5ixemPj

2025-01-03 00:30 UTC, laurenzlong approved these changes

2025-01-03 00:30 UTC, laurenzlong commented on providers/hubspot/subscriptionEvent.go
>  type SubscriptionEvent struct {
can you remove this commented out struct? otherwise it'll be tempting for others to revise the code to use this struct in the future, if you wanted to document what the message looks like, then maybe you can provide a sample message in a comment block.

2025-01-03 00:30 UTC, laurenzlong commented on providers/hubspot/subscriptionEvent.go
> +type SubscriptionEvent map[string]any
As discussed, going with a map is a good approach in order to preserve the full raw event body to send to builders (whereas JSON marshaling to/from a struct will lose the fields that are not captured in the struct definition). Can you please add a comment to explain this?

2025-01-03 00:56 UTC, jlimatampersand commented on providers/hubspot/subscriptionEvent.go
> +	portalId, err := m.AsInt("portalId")
Here as int returns int64, so below at line 109, the value should be casted to int as strconv.Itoa accepts int.

2025-01-03 19:48 UTC, laurenzlong approved these changes

2025-01-03 19:48 UTC, laurenzlong commented on common/map.go
> +type GenericMap map[string]any
Can you name this `StringMap`? Just because "generic" has a specific meaning in Go.

2025-01-03 19:48 UTC, laurenzlong commented on common/map.go
> +func (m GenericMap) Keys(key string) any {
This should return `[]string`, not any

2025-01-03 19:48 UTC, laurenzlong commented on common/map.go
> +var (
can you put these at the top of the file?

2025-01-03 19:48 UTC, laurenzlong commented on common/map.go
> +var errFieldTypeMismatch = errors.New("field type mismatch")
can you put this at the top of the file?

2025-01-03 19:48 UTC, laurenzlong commented on common/map.go
> +func assertType[T any](val any) (T, error) {
can you put this function below the other functions?

2025-01-03 19:48 UTC, laurenzlong commented on common/map.go
> +func (m GenericMap) Values() []any {
can you put the Values and Len function at the top, close to Keys? It makes more sense than interspersing among the the `Get` functions.

2025-01-03 19:48 UTC, laurenzlong commented on common/map.go
> +		values = append(values, v)
Similar to my comments on the Keys function, it's more efficient to not use append.

2025-01-03 19:48 UTC, laurenzlong commented on common/map.go
> +	keys := make([]any, 0, len(m))
keys are guaranteed to be strings, so this should be `[]string` not `[]any`

2025-01-03 19:48 UTC, laurenzlong commented on common/map.go
> +		keys = append(keys, k)
nit: append is less efficient. You can re-write as:

```
keys := make ([]string, len(m))
i := 0
for k := range m {
  keys[i] = k
  i++
}
return keys
```

2025-01-03 19:48 UTC, laurenzlong commented on common/map_test.go
> +func TestGenericMap(t *testing.T) {
once you rename GenericMap to StringMap, don't forget to update this test function also.

2025-01-03 19:48 UTC, laurenzlong commented on common/map_test.go
> +			if !slices.Contains(passes, k) {
I'm confused by what this is testing, this if statement will never be entered into, since you are iterating through `m` in the outer for loop, so `k` will always be one of the elements of `passes`

2025-01-03 19:48 UTC, laurenzlong commented on common/map_test.go
> +		passes := []string{"int"}
can you rename `passes` something like `keysWithIntValue` for clarity? Similarly for the other test cases in this file.

2025-01-03 19:48 UTC, laurenzlong commented on common/map_test.go
> +			if !slices.Contains(passes, k) {
After reading through the other test cases, this makes more sense, but it's better to just remove it since it's not testing anything for the regular `Get` function.

2025-01-03 19:48 UTC, laurenzlong commented on providers/hubspot/subscriptionEvent.go
> +SubscriptionEvent is a map[string]any on purpose because the structure of the event is not known.
can you add "as opposed to a typed struct"

2025-01-03 19:48 UTC, laurenzlong commented on common/types.go
> +type SubscriptionEventMap GenericMap
SubscriptionEventMap isn't used anywhere, and you already have SubscriptionEvent in the `subscriptionEvent.go` file, this should be removed.

2025-01-03 23:32 UTC, merged

2025-01-06 14:34 UTC, Cobalt0s commented on common/stringMap.go
> +type StringMap map[string]any
I think this type should live under `datautils` package as it is a new/similiar data type.