[ENG-907] feat: Add Mailchimp connector
amp-labs/connectors pull request #132
Opened 2024-03-28 10:28 UTC by Jkarage

## Checklist
- [x] Ran Linter
- [x] Catalog tests passing
- [x] Created PR from non-main branch 

## Catalog variables
datacenter/server-prefix which represents the servers hosting the Mailchimp. Used in the api base url. 

## Notes

## Testing 
### GET 
<img width="1157" alt="Screenshot 2024-03-27 at 16 26 33" src="https://github.com/amp-labs/connectors/assets/52887226/9c489096-5998-4676-b345-b2d10b5c83c3">

### POST
<img width="1145" alt="Screenshot 2024-03-27 at 18 27 41" src="https://github.com/amp-labs/connectors/assets/52887226/aec437ab-b81a-4dea-8efa-6fba5daad26c">

### PATCH
<img width="1157" alt="Screenshot 2024-03-28 at 12 01 26" src="https://github.com/amp-labs/connectors/assets/52887226/65538040-9039-4591-baa1-8dba89654f79">

### DELETE
<img width="1151" alt="Screenshot 2024-03-28 at 12 01 52" src="https://github.com/amp-labs/connectors/assets/52887226/8dc47ee9-d380-46b6-9318-3de7423dae19">

## Pagination
Requesting a paginated results of campaigns. We request a list of campaigns and by default we get 10 campaigns.
<img width="1144" alt="Screenshot 2024-03-28 at 13 22 05" src="https://github.com/amp-labs/connectors/assets/52887226/d83283af-065e-4718-9f50-b58f33da0253">

From the result above we can see there are 32 campaigns, We use query parameters `count` and `offset` to retrieve the remaining campaigns.
<img width="1147" alt="Screenshot 2024-03-28 at 13 21 17" src="https://github.com/amp-labs/connectors/assets/52887226/50449cd6-67f5-4512-a63e-4d16f454ed8b">

2024-03-28 10:28 UTC, Jkarage commented
@RajatPawar

2024-03-29 09:35 UTC, RajatPawar commented on providers/catalog.go
> +		BaseURL:  "https://{{.datacenter}}.api.mailchimp.com",
Can you please change this to `workspace`?

2024-03-29 09:36 UTC, RajatPawar requested changes
Please let me know once the changes are made, thanks!

2024-03-29 13:29 UTC, RajatPawar approved these changes

2024-03-29 13:29 UTC, RajatPawar commented on providers/catalog.go
> +	Capsule                             Provider = "capsule"
Can you please rebase?

2024-03-29 13:29 UTC, RajatPawar commented on providers/catalog.go
> +	Capsule                             Provider = "capsule"
Could you also please run `make fix`?

2024-03-29 13:35 UTC, Jkarage commented on providers/catalog.go
> +	Capsule                             Provider = "capsule"
Okay

2024-03-30 03:40 UTC, closed without merging