Aircall: add connector
amp-labs/connectors pull request #285
Opened 2024-05-07 09:50 UTC by Beadko

## Checklist
- [x] Ran Linter
- [x] Catalog tests passing
- [x] Created PR from non-main branch 

## Catalog variables
* {{scope}}

## Notes
Resolves #235 
Since the version is included in the base URL it should not be added when making an API call.

## Testing 
### GET 
URL: <localhost:4444/users> 
**Get all users**
![Screenshot 2567-05-07 at 15 43 03](https://github.com/amp-labs/connectors/assets/103050835/43ac78a5-d419-4ae3-bdec-171d924d5144)

### POST
URL: <localhost:4444/users> 
**Create a user**
![Screenshot 2567-05-07 at 15 40 27](https://github.com/amp-labs/connectors/assets/103050835/49204480-9d7f-459c-9918-52ae9b7afffe)

### PUT
URL: <localhost:4444/users/1292061> 
**Update a user**
![Screenshot 2567-05-07 at 16 07 28](https://github.com/amp-labs/connectors/assets/103050835/aa5d56a7-2238-4659-85ad-963750e8a89a)

### DELETE
URL: <localhost:4444/users/1292061> 
**Delete a user**
![Screenshot 2567-05-07 at 16 08 19](https://github.com/amp-labs/connectors/assets/103050835/7b131361-9aca-496b-96be-31dba85ba261)

## Pagination
URL:<localhost:4444/users?page=3&per_page=1>
**Get all users with pagination**
![Screenshot 2567-05-07 at 16 04 55](https://github.com/amp-labs/connectors/assets/103050835/9f357f44-72e1-434e-aa32-bc6920d00d09)

2024-05-13 14:55 UTC, RajatPawar commented on providers/catalog.go
> +		BaseURL:  "https://api.aircall.io/v1",
Also, can you please fix the merge conflicts along with this change? Thanks.

2024-05-13 14:55 UTC, RajatPawar requested changes
Needs a minor change.

2024-05-14 06:16 UTC, Beadko commented on providers/catalog.go
> +		BaseURL:  "https://api.aircall.io/v1",
Done, I have also added a commit to fix the go version format in go.mod

2024-05-14 13:39 UTC, RajatPawar approved these changes

2024-05-14 13:46 UTC, merged