Pipedrive Proxy Connector Integration Testing
amp-labs/connectors pull request #369
Opened 2024-05-17 11:30 UTC by Listener430

## Testing 
### GET 
URL: <https://proxy.withampersand.com/v1/deals?start=0&limit=5> 
![PD-proxy-get-ok](https://github.com/amp-labs/connectors/assets/95291462/6d08caf7-71a1-47de-935b-b41f1303c324)

### POST
URL: <https://proxy.withampersand.com/v1/deals> 
![PD-proxy-post-ok](https://github.com/amp-labs/connectors/assets/95291462/6cfa0f05-3318-4b25-81cc-a0651614455f)

### PUT
URL: <hhttps://proxy.withampersand.com/v1/deals/2> 
![PD-proxy-put-ok](https://github.com/amp-labs/connectors/assets/95291462/2d52022c-15d5-4989-a9b7-b9449fcbe7bd)
 ### DEL
URL: <hhttps://proxy.withampersand.com/v1/deals/2> 

### Invalid requests
Trying to delete a record that was already deleted
![PD-proxy-error](https://github.com/amp-labs/connectors/assets/95291462/3c96caad-ce91-4e0e-bda2-f631f3d99ad6)

## Pagination
First page, offset pagination, 2 parameters
![PD-pagination_first_page](https://github.com/amp-labs/connectors/assets/95291462/53afd5bc-e238-419f-abc1-f2a2529417e6)
Last page will contain the following code in the response
![PD-pagination_last_page](https://github.com/amp-labs/connectors/assets/95291462/e5098ff8-3dfd-4c81-91c3-f75e35e3f7e0)

## Successful console operation (operation & events)
![PD-proxy-operations-success](https://github.com/amp-labs/connectors/assets/95291462/043cc586-e03f-43ad-b066-0f6401371615)

## Failed console operation (operation & events)
![PD-proxy-operations-fail](https://github.com/amp-labs/connectors/assets/95291462/df157f05-4d0e-4a2d-b369-aa5c76a424cc)

## Raw token response
![PD-proxy-token-raw](https://github.com/amp-labs/connectors/assets/95291462/3b900008-8f04-48ef-891e-6be0f36b3bdf)

fixes #366

2024-05-20 13:27 UTC, RajatPawar requested changes

2024-05-20 13:27 UTC, RajatPawar commented on providers/catalog.go
Same as the other PR, can you please add `GrantType` to this?

2024-05-24 06:46 UTC, Listener430 commented on providers/catalog.go
Here is the requested change
https://github.com/amp-labs/connectors/pull/428

2024-06-03 06:16 UTC, Listener430 commented
@RajatPawar hi, the requested change was merged.

2024-06-03 09:48 UTC, RajatPawar approved these changes

2024-06-03 09:48 UTC, merged