ZohoCRM Integration Testing
amp-labs/connectors pull request #372
Opened 2024-05-20 05:18 UTC by Listener430

## Testing 
### GET 
URL: <https://proxy.withampersand.com/crm/v6/users/6172731000000476010> 
![Zoho-get-via-proxy](https://github.com/amp-labs/connectors/assets/95291462/30768c3e-ca0e-41be-a0dc-0df8ff7c8360)

### PUT
URL: <https://proxy.withampersand.com/crm/v6/users/6172731000000476010> 
![Zoho-put-via-proxy](https://github.com/amp-labs/connectors/assets/95291462/817747fc-5d5e-475d-8df6-f92310a5dd5a)

### Invalid requests
![Zoho-error-sampe3 (1)](https://github.com/amp-labs/connectors/assets/95291462/4b3a20d8-1a09-4473-b67b-7022587839b8)
![Zoho-error-sample_2](https://github.com/amp-labs/connectors/assets/95291462/7d226c11-b1aa-41bb-a38b-eb43da5347cb)
![Zoho-error_sample](https://github.com/amp-labs/connectors/assets/95291462/05bdb5d0-33d6-41f4-93f8-9b824105d0e2)

## Pagination
![Zoho-pagination](https://github.com/amp-labs/connectors/assets/95291462/1c713e05-10f8-4d5d-95f8-5fe02203b058)

## Successful console operation (operation & events)
![Zoho-successful-operations](https://github.com/amp-labs/connectors/assets/95291462/3057d627-9b4e-4f43-8211-d22f02622180)

## Failed console operation (operation & events)
![Zoho-failed-operations](https://github.com/amp-labs/connectors/assets/95291462/baa1fbae-0d22-4bea-bff7-2421430bfc7a)

## Raw token response
![token_raw](https://github.com/amp-labs/connectors/assets/95291462/ad885f57-e936-48bc-b7fd-7f5afbaafb54)

fixes#366

2024-05-20 13:25 UTC, RajatPawar requested changes

2024-05-20 13:25 UTC, RajatPawar commented on providers/catalog.go
Can you add the `GrantType` to this?

2024-05-21 07:17 UTC, Listener430 commented on providers/catalog.go
@RajatPawar thanks, please take a look at this PR with the changes - https://github.com/amp-labs/connectors/pull/393
Let me know if more changes to the auth part are required.

2024-05-22 07:36 UTC, RajatPawar approved these changes

2024-05-22 07:36 UTC, merged