Add Auth Connector for Facebook Ads Manager
amp-labs/connectors pull request #395
Opened 2024-05-21 08:44 UTC by Listener430

closes #283

2024-05-22 07:52 UTC, RajatPawar requested changes

2024-05-22 07:52 UTC, RajatPawar commented on providers/catalog.go
> +	// Faceboook Ads Manager Configuration
Typo here

2024-05-22 07:52 UTC, RajatPawar commented on providers/catalog.go
> +	FacebookAdsManager: {
Since this is the entire graph API, can you call this just `Facebook` and make sure to update the auth/token URLs if needed?

2024-05-23 09:02 UTC, closed without merging

2024-05-23 09:03 UTC, Listener430 commented
Changes were moved to https://github.com/amp-labs/connectors/pull/415