feat: Add Apollo connector
amp-labs/connectors pull request #532
Opened 2024-06-13 07:12 UTC by sanjay-a01

## Checklist

- [x] Ran Linter
- [x] Created PR from non-main branch 

## Notes
It supports Batching and pagination 

## Testing

### GET
URL: http://localhost:4444/v1/contact_stages
![image](https://github.com/amp-labs/connectors/assets/163011126/177d4114-1622-4302-a4eb-184211d33c4c)

### POST
URL: http://localhost:4444/v1/accounts
![image](https://github.com/amp-labs/connectors/assets/163011126/43399d45-dd9d-4416-bc3f-5ba51b768d00)

### PUT
URL: http://localhost:4444/v1/accounts/666a9a9bcc65ae03a1374cbb
![image](https://github.com/amp-labs/connectors/assets/163011126/e7c7cd70-6bd2-4a3b-9c67-7f816771c640)

### Pagination
Requesting a paginated list of accounts using per_page and page in the body:
URL: http://localhost:4444/v1/accounts/search
![image](https://github.com/amp-labs/connectors/assets/163011126/b1f4103b-abcb-4ccc-b812-bf03d30acfab)

Closes #521

2024-06-19 06:35 UTC, RajatPawar requested changes

2024-06-19 06:35 UTC, RajatPawar commented on providers/catalog.go
> +	ApolloIo: {
Can you rename this to `Apollo`?

2024-06-19 07:20 UTC, sanjay-a01 commented on providers/catalog.go
> +	ApolloIo: {
I have changed the name to Apollo

2024-07-08 14:39 UTC, RajatPawar approved these changes

2024-07-08 20:32 UTC, merged