feat: Deep connector Zendesk Support (Metadata)
amp-labs/connectors pull request #631
Opened 2024-06-29 18:26 UTC by Cobalt0s

[WIP]

Using OpenAPI to extract Metadata static file.

2024-07-11 14:09 UTC, Cobalt0s commented
* **#631** <a href="https://app.graphite.dev/github/pr/amp-labs/connectors/631?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `cobalt0s/zendesk-support`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Cobalt0s and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-16 11:19 UTC, Cobalt0s commented
@eberle1080  

Double checked Read/Write/Metadata scripts. All of them are passing.

![image](https://github.com/user-attachments/assets/27592ea4-43e3-460a-8f84-cbddcc1aa44e)

![image](https://github.com/user-attachments/assets/bcb430f3-8e43-454c-93dc-8df2e05f5c6f)

![image](https://github.com/user-attachments/assets/d3ddb32f-2293-4ee7-b537-612e0dfc5677)

2024-07-23 23:50 UTC, laurenzlong requested changes
@Cobalt0s I'm a bit confused the need for the aliases package, can you add comments (to `zendesksupport/metadata.go` to explain why we need to know about aliases in order to retrieve Zendesk object metadata? And if it is really needed by the Zendesk connector, can you move everything in handy/aliases.go to the zendesk connector? I am quite doubtful that another connector will need the aliases function.

2024-07-24 15:18 UTC, Cobalt0s reviewed
@eberle1080 

This PR was split into smaller chunks for easier review.
It also makes it explicit on how Zendesk Support and Pipeliner are related. Both use OpenAPI tool: https://github.com/amp-labs/connectors/pull/718

2024-07-24 15:18 UTC, Cobalt0s commented on zendesksupport/openapi/file.go
> +	FileManager = api3.NewOpenapiFileManager(apiFile) // nolint:gochecknoglobals
`support-api.yaml` is loaded into FileManager.

The script uses this FileManager along with the OpenAPI tool to produce `schemas.json`.

2024-07-24 15:18 UTC, Cobalt0s commented on scripts/scrapper/zendesksupport/metadata/main.go
> +		// problems -> additionalProperties
Some object names are stored under different alternative naming within openapi schema.
For Zendesk there are 3 exceptions.

Problems has no static fields, it is a free form map.

2024-07-25 13:40 UTC, closed without merging